development:
  adapter: mysql2
  database: jobsworth_dev
  username:
  encoding: utf8

test: &TEST
  adapter: mysql2
  database: jobsworth_test
  username:
  encoding: utf8

production:
  adapter: mysql2
  database: jobsworth
  username:
  encoding: utf8

cucumber:
  <<: *TEST
selenium:
  <<: *TEST

staging:
  adapter: mysql2
  database: jobsworth_staging
  host: HOST
  username:
  encoding: utf8
